# Generated by Django 5.1.6 on 2025-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='aidi',
            field=models.TextField(max_length=10),
        ),
    ]
